language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f swissroads_conda_env.yml
  - conda activate swissroads_conda_env
  - conda install sphinx sphinx_rtd_theme

script:
  # Run CI steps
  - nosetests -sv --with-coverage --cover-package=. test.py
  #- sphinx-build -b doctest doc sphinx

  # Build docs
  - sphinx-build doc sphinx
  - touch sphinx/.nojekyll
  - coveralls #uploads coverage report to coveralls.io

deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./sphinx/
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = 3.7


