language: python

python:
  - "3.6"

install:
  - pip install .
  - pip install -r build-requirements.txt

script:
  - rr-results  #test if the cmdline app runs at least
  - nosetests -sv --with-coverage --cover-package=rr rr #runs test
  - sphinx-build -b doctest doc sphinx
  - sphinx-build doc sphinx
  - touch sphinx/.nojekyll
  - coveralls #uploads coverage report to coveralls.io

deploy:
  - provider: pages:git
    verbose: true
    edge: true
    token: $GITHUB_TOKEN
    local_dir: ./sphinx/
    on:
      branch: master
      condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  - provider: pypi
    username: "__token__"
    password:
      secure: pypi-AgEIcHlwaS5vcmcCJGUzODcyNjk2LWY2OTUtNDI5ZS05NmNkLWM3MjdkZGE2ZWQxMgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgRUvbViW-LxgUHG7YL5j9robCjLv2zFzj66nbuluEDsg
    on:
      tags: true
      condition: "$TRAVIS_PYTHON_VERSION = 3.6"


